### ISSUE TITLE
issues in NODDI maps using MDT fitting

### ISSUE THREAD

**Issue by rosella1234** [robbert-harms/MDT#60]
I managed to install mdt via docker on a Centos7 server. I tried to fit this model on HCP data and fitting is very fast (about 6 minutes per subject). However, something goes wrong since NODDI maps look correct just for a small subset of slices on the left of the image, and the rest appear all white. I am attaching NDI for one subject as an example. How could I solve this issue?
thanks in advance,
Rosella
![IMG-20231120-WA0005](https://github.com/robbert-harms/MDT/assets/58302565/5ccc05ed-6c15-489c-a08a-ae5cf4ecbd82)

**Comment by robbert-harms** [comment]
Hi Rosella, this sometimes happens when there are too many voxels loaded at once into the GPU. You could add a file to your system in `~/.mdt/<version>/mdt.conf` with the content:

```
processing_strategies:
    optimization:
        max_nmr_voxels: 5000

    sampling:
        max_nmr_voxels: 1000
```

Or any sufficiently lower number. This should reduce the number of voxels in one batch and as such get rid of the problem.

Sorry for the slow reply, I had to take care of my son.

Best,

Robbert
